### ISSUE TITLE
Setting Allow multiple logins per team  - de-selected when other settings are updated

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#196] opened 2021-03-03 07:20 UTC
**Describe the issue**:

When certain settings on the Settings tab are updated
the Setting Allow multiple logins per team is unchecked/ de-selected 

There may be a number of Settings fields that cause 
this bug.

**To Reproduce**:

1. Start server, start admin
1. check ```Allow multiple logins per team ```
1. Update (to save it)
1. Edit Scoring Properties, Update then Update 

**Expected behavior**:

Allow multiple logins per team should be checked

**Actual behavior**:

Allow multiple logins per team it NOT checked

**Environment**:

**Log Info**:

**Screenshots**:

**Additional context**:

**Comment by lane55** [comment] 2021-03-21 03:50
Assigning to clevengr to verify that this issue is a dup of issue #206

**Comment by clevengr** [comment] 2021-03-21 04:14
Duplicate of #206... although THIS issue (in the "Steps to Reproduce" claims that the Allow Multiple Logins state is lost merely by editing/updating the Scoring Properties; I was never able to demonstrate that failure.  Rather, as stated in Issue #206, the state is lost when the Admin is _restarted_ after enabling the checkbox.

**Closed by clevengr** 2021-03-21 04:14 UTC
Labels: bug, duplicate, high priority
