### ISSUE TITLE
Event Feed JSON contains erroneous "contest ended" time.

### ISSUE THREAD

**Issue by clevengr** [pc2ccs/pc2v9#325] opened 2022-03-02 23:44 UTC
**Describe the issue**: 
A contest which lasted 8 days was run.  At the end, an Event Feed JSON report was generated (for input to the Resolver).  It contained the following lines:

```
{"type":"contests", "id":"pc2-1", "op":"create", "data": {"id":"Default--3440575228998471927","name":"PacNW22 Test Contest","formal_name":"Pacific NorthWest 2021 Test Contest","start_time":"2022-02-22T00:01:00.005-08","duration":"192:00:00","scoreboard_freeze_duration":"024:00:00","penalty_time":20}}

{"type":"state", "id":"pc2-2", "op":"create", "data": {"started":"2022-02-22T00:01:00.005-08","ended":"2074-04-23T09:02:00.010-07","frozen":"2022-03-01T00:01:00.005-08","finalized":"2022-03-02T00:17:01.180-08"}}
```
Note that the first line says the contest started on Feb 22, was scheduled to run for 8 days (192 hours), the scoreboard was scheduled to be frozen with 24 hours left.  All of this happened as stated.

Note that the second line says that the contest ended in year 2074.  That, uh, seems wrong.

**To Reproduce**:
Run a contest for several days, then generate an Event Feed JSON report; examine the "ended" time.   One might also be able to reproduce it with a shorter duration contest, although this hasn't been tested.

**Comment by lane55** [comment] 2022-03-03 01:33
The root cause for the bug was the ended date was the start date + the start date + the contest elapsed time.

**Comment by lane55** [comment] 2022-03-03 01:44
After fix shows proper ending date

 {"type":"state", "id":"pc2-2", "op":"create", "data": {"started":"2022-02-22T00:01:00.005-08","ended":"2022-03-02T00:01:00.005-08","frozen":"2022-03-01T00:01:00.005-08","finalized":"2022-03-02T00:17:01.180-08"}}

**Comment by lane55** [comment] 2022-03-03 01:55
The bug does not require a multi day contest.   A finalized contest before the fix will have a ended year as stated in
the description.

**Comment by lane55** [comment] 2022-03-10 18:32
PR approved, merged, closing issue.

**Closed by lane55** 2022-03-10 18:32 UTC
Labels: bug
