### ISSUE TITLE
On WTI web page interface, there is no way to tell what account is logged in

### ISSUE THREAD

**Issue by johnbrvc** [pc2ccs/pc2v9#863] opened 2023-11-16 13:59 UTC
**Is your feature request related to a problem?**
When a team logs into the WTI, there is no indication anywhere on any of the tabs or screen indicating what team is logged in.
This can help when someone is assisting a contestant, or proctoring a contest.

...

**Feature Description**: 
 Perhaps have the title bar of the web page say: "team98"  or, on every page in the header next to the ICPC log, have a big TEAM98 or something (see mockup attached).
...

**Have you considered other ways to accomplish the same thing?** 
No way to tell what team is currently logged in.
...

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?*
See attached.
...

**Additional context**: 
...
<img width="1099" alt="image" src="https://github.com/pc2ccs/pc2v9/assets/5657363/50676e9e-19ed-4213-a2a2-75d074454720">

**Comment by clevengr** [comment] 2023-11-18 00:48
This issue is very nearly a duplicate of https://github.com/pc2ccs/pc2v9/issues/690  (they both specify the same _issue_, although the two GitHub "Issues" have proposed considerably different _solution approaches_.)
- This here GitHub issue proposes displaying the Team Login name in the WTI title bar.
- Issue https://github.com/pc2ccs/pc2v9/issues/690 proposes changing the prompt on the Logoff button from simply "Logoff" to "Logoff Team XXX".

Either implementation would solve the underlying problem.  I am very much in favor of doing BOTH those things at the same time.

I'm marking this issue here as duplicate, mostly to help us keep track of things.  I would propose that THIS issue number (#863) be used for followup branch creation and PR submission work.

**Comment by clevengr** [comment] 2023-12-09 00:43
After having worked on this issue a bit, I retract my suggestion that "both those things [adding the logged-in user name to the header AND adding it to the logout button] should be done.   Once the team login is in the header, it is visible on every view as long as the team is logged in; there's no need to put it (redundantly) in the logout button as well. 

A PR which solves this issue (#863) should also be considered to solve (and hence, should also close) #690.

**Closed** 2023-12-14 05:49 UTC
Labels: duplicate, WTI-UI, Usability Issue, Small LOE, One Approval, Primary CCS
