### ISSUE TITLE
Auto-judge GUI makes desktop unusable while it's judging

### ISSUE THREAD

**Issue by johnbrvc** [pc2ccs/pc2v9#343] opened 2022-03-07 18:50 UTC
Thank you for working to help us improve PC^2!  
Please fill in the following fields in order to help us understand what issue you are reporting.

**Describe the issue**: 
On a machine that is auto-judging (pc2judge in AJ mode using **GUI**), the machine is virtually useless for anything while autojudging is enabled due to focus being lost.

**To Reproduce**:
Enable AJ (pc2judge gui) on a set of busy problems.  Then, try to do anything else on that computer once runs start coming in.
The pop-ups from AJ for each test case make it impossible to do anything.  

**Expected behavior**: 
The system should be usable while AJ is going on.   Maybe have an option on the AJ to not do popups for judging status
while judging (compiles, runs, etc).  (I am aware of the --nogui option, but it still would be nice if the GUI version didn't hog
the whole desktop by stealing focus).

**Actual behavior**:
The system loses focus constantly while pop-ups are displayed for judge cases.  Sometimes, typing while test cases are popping causes the judging of that problem to fail.  I think it's a function of what was being typed at the time the pop-up comes in.

**Environment**: please complete the following information:
 - Ubuntu 18.04
 - PC2 Version (e.g. 9.7.0):   9.7.0

**Log Info**: 
N/A  

**Screenshots**: 
N/A

**Additional context**: please add any other context about the issue here.

**Comment by lane55** [comment] 2022-03-20 22:02
One thought is to leverage the Auto Judge Status frame and simply update
the label with ongoing status that would previously be the focus stealing windows.

**Comment by clevengr** [comment] 2022-05-05 00:24
A couple of comments/suggestions on this Issue:
- Regarding the suggestion (above) that we might be able to leverage the Auto Judge Status Frame to avoid the problem identified in this Issue:
  - Based on past discussions and investigations, I believe that the constant "focus stealing" is because _every test case for a submission starts with a completely new instance of the `ExecuteTimer` class_ -- in which case simply moving the status updating to the Auto Judge Status Frame probably wouldn't solve the problem.   
- One approach we have talked about is to change the way in which the `Executable` class manages instances of the `ExecuteTimer` class so that there is a _single_ instance of `ExecuteTimer` created when a submission first starts being judged. The new `ExecuteTimer` would contain two JLabels:  **Status:**  and **Test Case:**
  - The **Status** field would change from "Compiling..." to "Executing..." to "Validating..." as the submission proceeds through the pipeline defined by class `Executable`.
  - The  **Test Case** field would be invisible during the "Compiling" phase.  During "Execution" and "Validation", the field would be continually updated to show the current Test Case number being processed.  
  - I don't _think_ the `setText()` calls to update those JLabels would generate change-of-focus events.  (If it does, some additional programming involving implementation of `FocusListener`s to capture lost and regained focus would be needed.)
- Implementing the above proposal is going to be non-trivial, because the use of `ExecuteTimer` is heavily entwined in the entire `Executable` pipeline.  For example, the `ExecuteTimer` is currently passed a reference to the (external) process which runs individual judging stages (for example, "execute submission" and "validate execution results").  See method `Executable.runProgram()`, which has as one of its parameters the current `ExecuteTimer` object.  The `ExecuteTimer` uses its external-process reference (set via a call to `ExecuteTimer.setProc()`) to manage the `IOCollector`s of the external process (e.g. the submission in execution, or the validator.)   It will take some careful refactoring (and testing) to make this work properly.
- Perhaps someone else can come up with a better/simpler approach to solving the problem.
- It's important to realize that fixing the "flashing GUI" and "focus stealing" is not going to make the rest of the machine available _for manual judging_.  There are conflicts when attempting to do AutoJudging and Manual Judging on the same machine (due to shared folders).  Of course, it would be nice to fix this issue so the machine **could** be used for _other_ things while running an AJ.

**Comment by lane55** [comment] 2022-05-05 01:51
This is an opportunity for a refactor as well as remove the flicker.

The flicker is caused because creation/control of the  JFrame (ivjExecuteTimerFrame) is within ExecuteTimer.

This frame and its methods, esp setText() should be moved out of ExecuteTimer and setVisible and disposed of
at a higher level in the code.   Add a listener or add a ExecuteTimerFrame instance to give access to the
.setText and .setTitle ExecuteTimerFrame  accessors.   This solution will still do a focus stealing.

To avoid the focus stealing entirely, use the AutoJudgeStatusFrame and use its label as the status/update,
perhaps adding another label if desired.

**Comment by lane55** [comment] 2022-05-05 01:53
Another refactor would be to use an observable pattern to update/log the text rather than hard
code the method used to update the ExecuteTimerFrame  text/info.

 With the observable interface of 
interface updateTimerLabels {
public void setText(String text);
public void setTitle(String title);
}
The interface would be passed as a constructor parameters for ExecuteTimer.

This requires a change in Executable where ExecuteTimer is instantiated,.
Another refactor would be to remove usingGUI from ExecuteTimer.  There could
be two implementations of updateTimerLabels, one for GUI the other for non-GUI.

**Comment by johnbrvc** [comment] 2022-05-05 12:21
One of the suggestions Doug made about using the "Waiting for Runs...." (AutoJudgeStatusFrame) and just
 updating that window's labels as judging progresses sounds like it may work best in terms of the focus / flickering
issues.  Really, when it comes down to it, the "Pop-ups" that are produced
during auto-judge are virtually useless since they often go by so quick you can't even tell what is going on, other than
"something is happening" since it's just opening and closing small windows.

The only pop-up that is somewhat useful is "Executing..." when a run takes a long time.  I think having the status text label
in the AJSF update as it's judging would work (implementing... well, that's another story and will require research).

Really, how many messages do we need as a run is being judged:

State 1: bigAutoJudgeStatusLabel: Waiting for Runs
State 2: bigAutoJudgeStatusLabel: Judging Run # for Team # Problem xxxxx
State 2: statusLabel: Compiling...
State 2: statusLabel: Executing case # of #
State 2: statusLabel: "" -> Go to State 1 when done judging

**Comment by lane55** [comment] 2022-05-05 16:27
> >  State 2: statusLabel: "" -> Go to State 1 when done judging
I would want to add "Judging complete" before State 1 
because I assume that each message will be logged.

**Comment by clevengr** [comment] 2022-05-05 17:52
*IF* simply moving status labels to the `AutoJudgeStatusFrame` will solve the problem, that's great.  However, I have my doubts because I think the problem we want to solve is constant "focus-stealing" and I think that it is the act of constantly disposing and reconstructing/displaying new instances of `ExecuteTimer` that is causing the focus-stealing.  If that's true, simply moving the status messages to the AJSF (although it would be a nice addition on its own) won't solve the problem.  As I noted in a previous comment, I think it's going to require rebuilding the "execution pipeline" (implemented in `Executable`) to fix this problem. But I'd be quite happy to be proved wrong...

**Comment by lane55** [comment] 2022-05-05 22:25
I am 99% sure that updating a label on a currently visible JFrame will steal focus.

If AutoJudgeStatusFrame  is made static/singleton and a method AutoJudgeStatusFrame  getInstance() is created then
the AutoJudgeStatusFrame  can be referenced from within ExecuteTimer  and there will be no change to 
Executable, and no change to the execution pipeline.

In ExecuteTimer all .setText methods could be replaced with new AutoJudgeStatusFrame.setText (or perhaps
a better named method like updateStateLabel and all references to the inner class ivjExecuteTimerFrame
can be removed.

**Comment by johnbrvc** [comment] 2022-05-06 13:18
Updating a label on a visible (or hidden) JFrame does *not* steal focus as shown in this little example I created using
AutoJudgeStatusFrame (it is stand-alone - I pulled out all the PC2 specific stuff.  Just build from command prompt using 'javac' and run using 'java'.)
[AutoJudgeStatusFrame.zip](https://github.com/pc2ccs/pc2v9/files/8640255/AutoJudgeStatusFrame.zip)

So, I think(??) this method may work... Still sorting through things...

**Comment by clevengr** [comment] 2022-05-06 17:00
John's test (above) matches what I suspected -- that updating a JLabel's text will not steal focus.  However, I still don't think this is really related to the problem.  

I'm saying that I think the problem is due to the repeated destruction and recreation of instances of `ExecuteTimer`.  I am pretty certain that a NEW `ExecuteTimer` is created for every compile/execute/validate step for each separate Test Case (and then disposed after that step is completed), and I think THAT is what is "stealing focus".  

I haven't written a test to verify that creating/making visible a new JFrame steals focus; that would seem to be the next step. 
 But if I'm right that a `JFrame.setVisible(true)` steals focus (or that there is some other action related to creating a new JFrame which steals focus), then it means the problem cannot be solved by changing the place where text is updated (such as moving it from `ExecuteTimer` to `AutoJudgeStatusFrame`); the only solution to the problem would appear to be to stop creating/disposing `ExecuteTimer` objects, and instead to use just ONE such object for the entire duration of judging a given submission (including executing all of its test cases).  It may be easy to do this -- but it will require careful examination of the entire execution pipeline.

**Comment by johnbrvc** [comment] 2022-05-06 17:32
Simply doing "setVIsible(false)" then "setVisible(true)" on the same JFRAME does not steal focus (I wouldn't expect it to).
In the actionListener of the sample I sent, right after the updateMessage(s) call, I inserted: setVIsible((nRun & 2) != 0);
So every 2 seconds it hides, then shows the JFrame, and it does not steal focus.

I do agree that creating a NEW JFrame steals focus (ExecuteTimerFrame).  Clearly, the code already "knows" how to not do this, since it supports the --nogui option, albeit with a completely different front-end interface (AutoJudgeModule).  
As mentioned above, it requires careful examination.   

Right now I am focusing on setting up a test-bed for shadowing, but I'll get back to this.

**Comment by johnbrvc** [comment] 2022-06-17 20:22
I have pushed a version that seems to work for both AJ and manual judging.
(branch: i_343_aj_makes_desktop_unusable_while_judging).
It takes everything above into consideration (that's not to say I did everything mentioned above, because there are several ideas mentioned).  Basically, I created a new class, ExecuteTimerFrame that is created in the Execute class once.  This is passed to into the ExecuteTimer's constructor for compiling, executing and validating.  A reset method is provided to reset the frame to it's "known" state since sometimes text color can change.  Visibility of the frame is managed by the Execute class in the "execute(...)" method and removed form the ExecuteTimer completely.  A notification interface is provided to let the ExecuteTimer know if the Terminate button was pressed.

Oh, as a CI i made the window show the test case number it is executing/validating (separate commit).

Basic testing with both AJ and Manual judging appears to work.  And, oh my, is it faster!  Wow.  The test case numbers
fly by in a blur if the program runs quickly.

**Comment by lane55** [comment] 2022-06-18 13:58
Yes, this works better but the new class still steals focus.

The solution must not steal focus.   Leveraging the existing Auto Judge Status (class AutoJudgeStatusFrame)
and adding labels will meet that goal.

There is another implementation error which is if there are 120 test cases there is no practical way to
Terminate the testing.    There was before, esp when there were test cases that ran longer than 5 seconds.
(Added issue https://github.com/pc2ccs/pc2v9/issues/462)

**Comment by lane55** [comment] 2022-06-18 13:59
I suggest adding a listener to AutoJudgeStatusFrame that will provide a way update the labels.

**Comment by johnbrvc** [comment] 2022-06-18 15:23
> 

I assume you mean it steals focus ONLY when an AJ starts judging a new run, not for the individual test cases, correct?  That is,
AJ is quiescent,  you have focus in another window and are trying to type something.  Then, a run comes in.  The ExecuteTimerFrame pops up at the START of the AJ for the new run, and you lose focus.  However, if it is executing, say, 58 or 100 test cases, it does NOT steal focus during that time.  Is that correct?  I tried putting a "listener" type thing in to handle the label updates using an "invoke later" type thing, and the status messages displayed were not reflecting reality (they were somewhat delayed).  This is why I opted to have the ExecuteTimer directly update the labels.  I suppose I could have the "listener" directly update the labels and not "invoke later" if you think that is cleaner.  To me, a "listener" should not silently "block" whoever is firing off the event, which it would do if it updated the label directly.

**Comment by johnbrvc** [comment] 2022-06-18 15:32
> 

I'm not sure what you mean.  Is this something new w/r/t my new implementation of ExecuteTimerFrame?  I didn't observe this issue in my testing, in fact, I used it quite often since I was not willing to wait for all 56 test cases I had.  It is very easy to select the terminate button, since it is the same one - it is not created over and over like before.  I did not try your exact test, I used my own which  has 56 test cases where each run takes practically no time, but it does take SOME time (50-100ms?)  Is it possible, that the runs are happening so fast in your case, that when the button is pressed, you are between test cases and there is no ExecuteTimer to notify that the button was pressed?  In this case, an interface method could be added to have ExecuteTimer check if the button was pressed in the ExecuteTimerFrame (or equivalent) before it starts?

**Comment by johnbrvc** [comment] 2022-06-20 14:15
As a follow-up, I did investigate leveraging of AutoJudgeStatusFrame,   I convinced myself it wouldn't work for us.  While it looks enticing, it's fools gold.  There is already a nice interface (AutoJudgeNotifyMessage) that does mostly what @lane55 suggests.  The problem is several other classes use the Executable class that don't have an AutoJudgeStatusFrame to use: 
 
EditRunPane
SelectJudgementPane
SubmitRunPane (for Test button)
TestResultsPane (kinda-sorta)

The only class that creates an AutoJudgeStatusFrame is AutoJudgingMonitor.  The other ones **count** on a frame being created for it (which ExecuteTimer was more than happy to do for everyone: ivjExecuteTimerFrame).  So, what I did was to create a frame one level up from ExecuteTimer in Executable, the new "ExecuteTimerFrame".    The problem with this as @lane55 pointed out, is when the AJ goes to judge a run, it creates a new Executable object, which creates a new ExecuteTimerFrame, which, steals focus at the start of judging that run.  One possibility here is to make this member static, initialize it the first time through, then going forward everyone uses the same one.   While this could work, I think it's a like kludgy making a static member to do something like this (for a heavy object like a JFrame).

It was suggested to make the "AutoJudgeStatusFrame" a static so ExecuteTImer could use it over and over.  This won't work
right for the 4 classes mentioned above and it's kind of kludgy.

An option I considered is to create an interface that is passed to Executable, (kind of like AutoJudgeNotifyMessage).  AutoJudgingMonitor could use AutoJudgeStatusFrame (which will also implement this new interface), and the other 4 classes could use the new class I already created, ExecuteTimerFrame, which would implement the new interface (they'd each have to create an instance of it and pass it to Executable).

Does this last option sound reasonable?

**Closed** 2023-04-29 05:11 UTC
