### ISSUE TITLE
Add CCS API version object/info

### ISSUE THREAD

**Issue by lane55** [pc2ccs/pc2v9#581] opened 2022-10-29 20:23 UTC
**Is your feature request related to a problem?** 

Per CCS https://ccs-specs.icpc.io/2022-07/contest_api#api-information
add GET API for version object

**Feature Description**: 

GET https://example.com/api/ returns information (below)

**Have you considered other ways to accomplish the same thing?** 

n/a

**Do you have any specific suggestions for how your feature would be ***implemented*** in PC^2?**

Add endpoint

**Additional context**: 

Per CCS API returns, something similar to 

{
   "version": "2022-07",
   "version_url": "https://ccs-specs.icpc.io/2022-07/contest_api",
   "name": "Kattis",
   "logo": [{
      "href": "/api/logo",
      "hash": "36dcf7975b179447783cdfc857ce9ae0",
      "filename": "logo.png",
      "mime": "image/png",
      "width": 600,
      "height": 600
   }]
}

**Comment by clevengr** [comment] 2023-10-12 02:07
This is a duplicate of Issue #725, which was closed as a result of PR #726.

**Closed by clevengr** 2023-10-12 02:07 UTC
Labels: enhancement, good first issue, CLICS CCS Update
